[tool.black]
line-length = 100

[tool.isort]
profile = "black"
src_paths = ["tests"]

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"